// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // The CLI (migrate deploy / seed) needs a DIRECT, unpooled connection —
    // running migrations over a PgBouncer transaction pooler can fail on
    // prepared statements. Prefer DIRECT_URL when set (unpooled); else fall
    // back to DATABASE_URL (same as the app, for local/docker).
    url: process.env["DIRECT_URL"] ?? process.env["DATABASE_URL"],
  },
});
